import "@/app/globals.css";
import { SiteHeader } from "@/components/site-header";
import GlobalCanvas from "@/globals/global-canvas";
import GlobalModal from "@/globals/global-modal";
import { requireAuthWithRedirections } from "@/lib/auth/require-auth-with-redirections";
import SessionProvider from "@/providers/session-provider";
import { ThemeProvider } from "@/providers/theme-provider";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  await requireAuthWithRedirections();
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <SessionProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <SiteHeader />
            <main>{children}</main>
            <GlobalModal />
            <GlobalCanvas />
          </ThemeProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
